version: '3.8'

services:
  # --- 1. VERİTABANI (MONGODB) ---
  mongo:
    image: mongo:latest
    container_name: chattalk_db
    ports:
      - "27017:27017" # Studio 3T ile bağlanabilmen için
    volumes:
      - mongo-data:/data/db 
    networks:
      - mern-network

  # --- 2. BACKEND (API) ---
  api:
    build: ./server
    container_name: chattalk_api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chattalk
      - PORT=5000
    env_file:
      - ./server/.env
    volumes:
      # BİLGİSAYARDAKİ uploads KLASÖRÜNÜ KONTEYNERA BAĞLA
      - ./server/uploads:/app/uploads
      # Kod değişince server'ı yeniden başlatmak istersen (Geliştirme için opsiyonel)
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - mern-network

  # --- 3. FRONTEND (CLIENT) ---
  client:
    build:
      context: ./client
      args:
        VITE_API_URL: /api 
    container_name: chattalk_client
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api
    networks:
      - mern-network
# --- AĞ VE DEPOLAMA AYARLARI ---
networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
# end